### ISSUE TITLE
Docker build failing

### ISSUE THREAD

**Issue by pitastrudl** [badgeteam/badgehub-frontend#1]
Hi,

I was trying to build the container locally and it seems it wants something else to run locally? I am guessing it's the badgehub api judging by this line 

```javascript
const DEFAULT_API_ROUTE = "http://localhost:8001/api/v3";

```
Build log: 

```Dockerfile
 => [app deps 3/4] COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./                                  0.1s
 => [app deps 4/4] RUN   if [ -f yarn.lock ]; then yarn --frozen-lockfile;   elif [ -f package-lock.json ]; then npm  38.0s
 => [app builder 2/4] COPY --from=deps /app/node_modules ./node_modules                                               22.4s
 => [app builder 3/4] COPY . .                                                                                         2.5s
 => ERROR [app builder 4/4] RUN   if [ -f yarn.lock ]; then yarn run build;   elif [ -f package-lock.json ]; then np  39.4s
------
 > [app builder 4/4] RUN   if [ -f yarn.lock ]; then yarn run build;   elif [ -f package-lock.json ]; then npm run build;   elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm run build;   else echo "Lockfile not found." && exit 1;   fi:
1.569 
1.569 > badgehub-web@0.1.0 build
1.569 > next build
1.569 
3.504 Attention: Next.js now collects completely anonymous telemetry regarding usage.
3.505 This information is used to shape Next.js' roadmap and prioritize features.
3.505 You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
3.505 https://nextjs.org/telemetry
3.505 
4.222   ▲ Next.js 14.2.5
4.222 
4.815    Creating an optimized production build ...
26.33  ✓ Compiled successfully
26.33    Linting and checking validity of types ...
33.50    Collecting page data ...
36.72    Generating static pages (0/7) ...
37.14    Generating static pages (1/7) 
37.67 TypeError: fetch failed
37.67     at node:internal/deps/undici/undici:12618:11
37.67     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
37.67     at async n (/app/.next/server/app/apps/[slug]/page.js:1:4232)
37.67     at async l (/app/.next/server/app/apps/page.js:1:3024) {
37.67   cause: Error: connect ECONNREFUSED ::1:8001
37.67       at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
37.67       at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:128:17) {
37.67     errno: -111,
37.67     code: 'ECONNREFUSED',
37.67     syscall: 'connect',
37.67     address: '::1',
37.67     port: 8001
37.67   },
37.67   digest: '1641787486'
37.67 }
37.67 TypeError: fetch failed
37.67     at node:internal/deps/undici/undici:12618:11
37.67     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
37.67     at async n (/app/.next/server/app/apps/[slug]/page.js:1:4232)
37.67     at async l (/app/.next/server/app/apps/page.js:1:3024) {
37.67   cause: Error: connect ECONNREFUSED ::1:8001
37.67       at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
37.67       at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:128:17) {
37.67     errno: -111,
37.67     code: 'ECONNREFUSED',
37.67     syscall: 'connect',
37.67     address: '::1',
37.67     port: 8001
37.67   },
37.67   digest: '1641787486'
37.67 }
37.67 TypeError: fetch failed
37.67     at node:internal/deps/undici/undici:12618:11
37.67     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
37.67     at async n (/app/.next/server/app/apps/[slug]/page.js:1:4232)
37.67     at async l (/app/.next/server/app/apps/page.js:1:3024) {
37.67   cause: Error: connect ECONNREFUSED ::1:8001
37.67       at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
37.67       at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:128:17) {
37.67     errno: -111,
37.67     code: 'ECONNREFUSED',
37.67     syscall: 'connect',
37.67     address: '::1',
37.67     port: 8001
37.67   },
37.67   digest: '1641787486'
37.67 }
37.67 
37.67 Error occurred prerendering page "/apps". Read more: https://nextjs.org/docs/messages/prerender-error
37.67 
37.67 TypeError: fetch failed
37.67     at node:internal/deps/undici/undici:12618:11
37.67     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
37.67     at async n (/app/.next/server/app/apps/[slug]/page.js:1:4232)
37.67     at async l (/app/.next/server/app/apps/page.js:1:3024)
37.67    Generating static pages (3/7) 
37.76    Generating static pages (5/7) 
37.82  ✓ Generating static pages (7/7)
37.91 
37.91 > Export encountered errors on following paths:
37.91   /apps/page: /apps
37.96 npm notice
37.96 npm notice New minor version of npm available! 10.7.0 -> 10.8.2
37.96 npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.8.2
37.96 npm notice To update run: npm install -g npm@10.8.2
37.96 npm notice
------
failed to solve: process "/bin/sh -c if [ -f yarn.lock ]; then yarn run build;   elif [ -f package-lock.json ]; then npm run build;   elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm run build;   else echo \"Lockfile not found.\" && exit 1;   fi" did not complete successfully: exit code: 1
```

**Comment by edwinm** [comment]
DEFAULT_API_ROUTE pointing to localhost is only for local development. I'm sure it's fixed now and I'll close this issue.
